refatorar listcategories para classes com sass modules
MeAjudaDev/greenwallet-react pull request #17
Opened 2021-07-02 11:17 UTC by stenioas

2021-07-02 11:18 UTC, stenioas commented
![](https://github.trello.services/images/mini-trello-icon.png) [[bqxcEGxW]Refatorar página ListCategories para classes com Sass Module](https://trello.com/c/bqxcEGxW/84-bqxcegxwrefatorar-p%C3%A1gina-listcategories-para-classes-com-sass-module)

2021-07-02 11:30 UTC, weescoelho requested changes

2021-07-02 11:30 UTC, weescoelho commented on src/pages/ListCategories/ListCategories.module.scss
>      color: #afb3bb;
Esta cor não está constando no arquivo variables.modules.scss? Seria interessante inclui-la.

2021-07-02 12:56 UTC, stenioas commented on src/pages/ListCategories/ListCategories.module.scss
>      color: #afb3bb;
Não consta. Alterei para uma cor já existente.

2021-07-03 13:57 UTC, francisrod01 approved these changes

2021-07-03 18:44 UTC, weescoelho approved these changes

2021-07-03 18:46 UTC, merged