Feature/z of l sf nz create form select
MeAjudaDev/greenwallet-react pull request #20
Opened 2021-07-03 21:26 UTC by gstvz

2021-07-03 21:29 UTC, angelomarques commented
![](https://github.trello.services/images/mini-trello-icon.png) [[ZOfLSfNz] - Criar componente Form Select](https://trello.com/c/ZOfLSfNz/58-zoflsfnz-criar-componente-form-select)

2021-07-04 00:27 UTC, stenioas requested changes

2021-07-04 00:27 UTC, stenioas commented on src/components/Select/Select.jsx
> +import Styles from "./Select.module.scss";
Seria interessante manter o padrão com letras minúsculas no "styles"

2021-07-04 00:27 UTC, stenioas commented on src/components/Select/Select.jsx
> +import arrow from "../../assets/dropdown-icon.svg";
Poderia usar o padrão "imgArrow" para os imports de imagem

2021-07-04 00:27 UTC, stenioas commented on src/routes/index.js
> +import Select from "../components/Select";
Alterações no arquivo de rotas para testar o componente deveriam estar sendo commitadas?

2021-07-04 12:17 UTC, stenioas approved these changes

2021-07-07 02:15 UTC, oiagorodrigues commented on src/components/Select/Select.jsx
> +    options = [
Não seria melhor passar um array vazio como valor default?

2021-07-07 02:15 UTC, oiagorodrigues commented on src/components/Select/Select.jsx
> +                    backgroundImage: "url(" + imgArrow + ") no-repeat right #ddd",
Você consegue fazer isso no scss também. É só passar `background-image: url(caminho-para-arquivo);`.

2021-07-07 11:20 UTC, weescoelho requested changes

2021-07-07 11:20 UTC, weescoelho commented on src/components/Select/Select.jsx
> +            <img src={arrow} alt="" />
Adicionar alt da imagem para acessibilidade.

2021-07-07 22:16 UTC, andremarcondesteixeira requested changes
sugestões iguais às do Iago

2021-07-08 04:30 UTC, francisrod01 approved these changes

2021-07-08 11:18 UTC, weescoelho approved these changes

2021-07-08 11:46 UTC, oiagorodrigues approved these changes

2021-07-10 19:15 UTC, andremarcondesteixeira requested changes

2021-07-10 19:15 UTC, andremarcondesteixeira commented on src/components/Select/Select.jsx
> +                    <option value={option.value}>{option.label} </option>
remover o espaço depois de {option.label}

2021-07-10 19:18 UTC, andremarcondesteixeira approved these changes

2021-07-10 19:18 UTC, merged