[UehWfjPC] (RF28/30) - Criar componente ExportModal
MeAjudaDev/greenwallet-react pull request #22
Opened 2021-07-07 23:36 UTC by angelomarques

2021-07-08 20:49 UTC, weescoelho requested changes

2021-07-08 20:49 UTC, weescoelho commented on src/routes/index.js
> +                <Route path="/modal">
Não há necessidade para criar uma rota para o modal. Acredito que há melhor forma de aciona-lo é via estado.

2021-07-08 20:49 UTC, weescoelho commented on src/components/ExportModal/ExportModal.jsx
> +                <h2>Export</h2>
Alterar para "Exportar"

2021-07-08 20:55 UTC, weescoelho approved these changes

2021-07-08 22:56 UTC, stenioas commented
![](https://github.trello.services/images/mini-trello-icon.png) [[UehWfjPC] (RF28/30) - Criar componente ExportModal](https://trello.com/c/UehWfjPC/65-uehwfjpc-rf28-30-criar-componente-exportmodal)

2021-07-10 19:13 UTC, andremarcondesteixeira requested changes

2021-07-10 19:13 UTC, andremarcondesteixeira commented on src/App.jsx
> +     <Routes/>
Acho que a indentação foi desfeita por acidente aqui. Reverter.

2021-07-10 19:13 UTC, andremarcondesteixeira commented on src/components/ExportModal/ExportModal.module.scss
> +    h3 {
inserir quebra de linha antes do h3

2021-07-10 19:13 UTC, andremarcondesteixeira commented on src/components/ExportModal/ExportModal.module.scss
> +        &::-webkit-calendar-picker-indicator {
inserir quebra de linha antes deste seletor

2021-07-10 19:13 UTC, andremarcondesteixeira commented on src/components/InputDate/InputDate.module.scss
>      img {
inserir quebra de linha antes do seletor do img

2021-07-10 19:23 UTC, andremarcondesteixeira approved these changes

2021-07-10 19:26 UTC, merged