Feature/pli fc dwc create form circle button
MeAjudaDev/greenwallet-react pull request #24
Opened 2021-07-14 22:48 UTC by gstvz

2021-07-14 22:49 UTC, gstvz commented
![](https://github.trello.services/images/mini-trello-icon.png) [[pliFCDwc] - Criar componente Form Circle Button](https://trello.com/c/pliFCDwc/64-plifcdwc-criar-componente-form-circle-button)

2021-07-14 23:33 UTC, francisrod01 commented on src/components/CircleButton/CircleButton.jsx
> + * Usage:
Decidimos criar um comentário de "usage" para ajudar no uso do componente nas telas, já que não estamos usando o componente em nenhum lugar.

2021-07-14 23:33 UTC, francisrod01 commented on src/components/CircleButton/CircleButton.jsx
> +                [styles.primary]: props.primary,
Foram removidas as demais propriedades de estilo, conforme conversamos na daily.

2021-07-14 23:34 UTC, francisrod01 commented on src/components/CircleButton/CircleButton.jsx
> +            <img src={props.icon} />
Passamos o ícone por props para o componente do botão.

2021-07-14 23:34 UTC, francisrod01 approved these changes

2021-07-15 17:25 UTC, weescoelho requested changes

2021-07-15 17:25 UTC, weescoelho commented on src/components/CircleButton/CircleButton.jsx
> +            <img src={props.icon} />
Adicionar o alt da imagem para acessibilidade.

2021-07-15 17:29 UTC, weescoelho requested changes

2021-07-15 17:29 UTC, weescoelho commented on src/components/CircleButton/CircleButton.jsx
> +export default function CircleButton(props) {
Acredito que seria interessante passar o alt da imagem via prop, de acordo com o tipo do botão.

2021-07-15 18:51 UTC, francisrod01 commented on src/components/CircleButton/CircleButton.jsx
> +export default function CircleButton(props) {
Bem lembrado! Respeitando os padrões de acessibilidade.

2021-07-16 21:18 UTC, stenioas approved these changes

2021-07-19 22:16 UTC, andremarcondesteixeira approved these changes

2021-07-19 22:37 UTC, merged