refactor: css variables converted to scss in index.css
MeAjudaDev/greenwallet-react pull request #3
Opened 2021-06-13 21:26 UTC by Gabriel-P22

css variables converted to scss in index.css

2021-06-14 11:44 UTC, weescoelho commented
Show Gabriel. Eu recomendaria tirar as variaveis de dentro do :root. No Sass não há necessidade que as variaveis sejam declaradas dentro de uma tag e tambem não necessita usar o var().

2021-06-14 22:20 UTC, stenioas commented
![](https://github.trello.services/images/mini-trello-icon.png) [Refatorar variaveis do index.css para variaveis do Sass](https://trello.com/c/wVeK0PeI/52-refatorar-variaveis-do-indexcss-para-variaveis-do-sass)

2021-06-14 22:57 UTC, francisrod01 approved these changes

2021-06-15 02:05 UTC, andremarcondesteixeira requested changes

2021-06-15 02:05 UTC, andremarcondesteixeira commented on src/index.scss
> +    $border-radius-default: 6px;
Parece que o Sass não precisa que variáveis estejam dentro de root

2021-06-15 02:05 UTC, andremarcondesteixeira commented on src/index.scss
> +    background-color: var($color-background-default);
Ao que parece, o Sass não precisa usar a função var

2021-06-15 04:16 UTC, stenioas commented on src/index.scss
> +$color-danger: #ff7e78;
Variáveis chamadas antes de serem declaradas aparentemente não sofrem hoisting com em JS. Reordenei.

2021-06-15 04:18 UTC, stenioas commented on src/index.jsx
> +import "./index.scss";
Esqueci de declarar essa alteração no commit.

2021-06-15 04:18 UTC, stenioas approved these changes

2021-06-15 12:10 UTC, weescoelho approved these changes

2021-06-16 22:18 UTC, stenioas approved these changes

2021-06-16 22:34 UTC, francisrod01 approved these changes

2021-06-16 22:34 UTC, merged