feat(editcategory): refactored EditCategory Page with SASS Modules
MeAjudaDev/greenwallet-react pull request #33
Opened 2021-08-23 23:55 UTC by gstvz

Galera, fiz a tela com base no design antigo (que era da squad de Vue, acho).

Removi o handleCheckboxChange, porque a tela usa Radio.

Preciso de ideias pra aplicar espaçamento entre os botões de Salvar e Voltar.

![Tela](https://user-images.githubusercontent.com/79481036/130534110-132ccda4-0d92-4eca-94b8-0682cc528fdc.jpg)

2021-08-23 23:56 UTC, gstvz commented
![](https://github.trello.services/images/mini-trello-icon.png) [[g23H26KL]Refatorar página EditCategory para classes com Sass Module](https://trello.com/c/g23H26KL/83-g23h26klrefatorar-p%C3%A1gina-editcategory-para-classes-com-sass-module)

2021-08-24 00:12 UTC, francisrod01 commented on src/pages/EditCategory/EditCategory.jsx
> +
```suggestion

```

Há espaços em branco no código

2021-08-24 00:13 UTC, francisrod01 commented on src/pages/EditCategory/EditCategory.jsx
> +
```suggestion

```

Eu sou fã do eslint, pois reforça a formatação do código.
https://github.com/eslint/eslint

2021-08-24 00:14 UTC, francisrod01 approved these changes

2021-08-24 03:18 UTC, stenioas approved these changes

2021-08-25 14:19 UTC, gstvz commented
Removi os espaços em branco citados pelo Francis. Criei uma div para os botões e uma classe para ela e para a div do conteúdo do form. Apliquei flex e flex gap na div dos botões com spacing-small. Ficou ok o espaçamento?

2021-08-27 17:51 UTC, oiagorodrigues requested changes

2021-08-27 17:51 UTC, oiagorodrigues commented on src/pages/EditCategory/EditCategory.jsx
> +                <Button type="submit" secondary>Voltar</Button>
```suggestion
                <Button type="button" secondary>Voltar</Button>
```

Sugiro remover o `type="submit"` desse botão **Voltar**, para que ele não submita o formulário quando for ativado.

2021-08-27 17:51 UTC, oiagorodrigues approved these changes

2021-08-27 17:53 UTC, oiagorodrigues commented
Muito bom @gstvz. 
Não sabia que podia usar o `gap` em Flexbox também. 
Isso é uma ajuda tremenda!

2021-08-29 12:25 UTC, gstvz commented on src/pages/EditCategory/EditCategory.jsx
> +                <Button type="submit" secondary>Voltar</Button>
Bem observado, acabou passando batido

2021-08-29 12:27 UTC, gstvz commented
@oiagorodrigues créditos ao @stenioas e ao @francisrod01 que deram a ideia, hehehe

Fiz a correção do type nesse último commit, creio que agora está tudo ok

2021-09-06 22:27 UTC, merged