Feature/criar componente cabecalho
MeAjudaDev/greenwallet-react pull request #4
Opened 2021-06-13 23:08 UTC by Gabriel-P22

header component finished

2021-06-14 03:35 UTC, francisrod01 approved these changes

2021-06-14 03:35 UTC, francisrod01 commented on src/index.jsx
> +         <ExpenseForm title="Editar Despesa" isEditing={true} />
Penso que está na hora de usar um lint para formatação de código.

```suggestion
        <ExpenseForm title="Editar Despesa" isEditing={true} />
```

2021-06-14 05:58 UTC, stenioas commented on src/index.jsx
> +         <ExpenseForm title="Editar Despesa" isEditing={true} />
Seria uma boa, Francis!

2021-06-14 14:24 UTC, angelomarques approved these changes

2021-06-14 22:21 UTC, stenioas commented
![](https://github.trello.services/images/mini-trello-icon.png) [Criar componente de cabeçalho com novo design](https://trello.com/c/DPR46fjK/50-criar-componente-de-cabe%C3%A7alho-com-novo-design)

2021-06-15 02:04 UTC, andremarcondesteixeira requested changes

2021-06-15 02:04 UTC, andremarcondesteixeira commented on src/components/Header/Header.jsx
> +export default Header
deixar o export default junto da definição da função na linha 4.

2021-06-15 02:04 UTC, andremarcondesteixeira commented on src/index.jsx
> +         <ExpenseForm title="Editar Despesa" isEditing={true} />
Identar o código

2021-06-15 02:04 UTC, andremarcondesteixeira commented on src/components/Header/Header.jsx
> +function Header(props) {
Apagar o componente `AppHeader` que já existia e colocar esse no lugar. Não se esqueça de procurar os locais onde o componente antigo era usado e substitua pelo novo.

2021-06-15 03:38 UTC, stenioas commented on src/components/Header/Header.jsx
> +function Header(props) {
Mudanças realizada!

2021-06-15 03:40 UTC, stenioas approved these changes

2021-06-15 03:45 UTC, francisrod01 approved these changes

2021-06-16 22:17 UTC, stenioas approved these changes

2021-06-16 22:19 UTC, francisrod01 commented on src/components/Header/Header.jsx
> +import styles from './Header.module.scss'
Não se esqueçam de usar ponto e vírgula. ;)

2021-06-16 22:20 UTC, francisrod01 commented on src/components/Header/index.js
> +export { default } from './Header'
Também faltou ponto e vírgula no final.

2021-06-16 22:23 UTC, francisrod01 approved these changes

2021-06-16 22:24 UTC, merged