Feature/lztk l dqa refatorar componentes utilizando sass modules
MeAjudaDev/greenwallet-react pull request #5
Opened 2021-06-14 23:59 UTC by francisrod01

closes issue.

2021-06-15 00:17 UTC, rayanaprata commented
![](https://github.trello.services/images/mini-trello-icon.png) [[LztkLDqa] Refatorar componentes utilizando Sass Modules](https://trello.com/c/LztkLDqa/51-lztkldqa-refatorar-componentes-utilizando-sass-modules)

2021-06-15 02:01 UTC, andremarcondesteixeira requested changes

2021-06-15 02:01 UTC, andremarcondesteixeira commented on src/components/MonthsNavBar/MonthsNavBar.jsx
> +                            className={`${styles.link} ${item.selected ? 'active' : ''}`}
precisamos definir um padrão de formatação de quebra de linha para tags com múltiplas linhas. Sugestões?

2021-06-15 03:37 UTC, francisrod01 commented on src/components/MonthsNavBar/MonthsNavBar.jsx
> +                            className={`${styles.link} ${item.selected ? 'active' : ''}`}
Algumas sugestões:

- Extrair o padrão que o git hook `husky` faz, ou utilizá-lo (não consegui encontrar na doc nenhum exemplo).
- Utilizar `eslint` com padrão `recommended` para começarmos a seguir uma convenção de código.

2021-06-16 22:20 UTC, angelomarques approved these changes

2021-06-16 23:11 UTC, Gabriel-P22 approved these changes

2021-06-19 21:41 UTC, andremarcondesteixeira approved these changes

2021-06-19 21:41 UTC, merged