Feature/ng iq2 td5 criar menu
MeAjudaDev/greenwallet-react pull request #6
Opened 2021-06-15 23:27 UTC by angelomarques

2021-06-15 23:27 UTC, weescoelho commented
![](https://github.trello.services/images/mini-trello-icon.png) [[NgIq2Td5] Criar menu de navegação](https://trello.com/c/NgIq2Td5/41-ngiq2td5-criar-menu-de-navega%C3%A7%C3%A3o)

2021-06-15 23:58 UTC, francisrod01 commented on src/components/Menu/Menu.jsx
> +function Menu() {
Poderíamos usar o export default na criação da função.

2021-06-15 23:59 UTC, francisrod01 approved these changes

2021-06-16 00:36 UTC, stenioas requested changes

2021-06-16 00:36 UTC, stenioas commented on src/components/Menu/Menu.module.scss
> +    left:0%
Sugestão: left: 0;

2021-06-16 22:09 UTC, weescoelho commented on src/components/Menu/Menu.module.scss
> +    left:0%
Resolvido

2021-06-16 23:05 UTC, francisrod01 approved these changes

2021-06-17 00:49 UTC, andremarcondesteixeira approved these changes

2021-06-17 01:54 UTC, francisrod01 approved these changes

2021-06-17 02:13 UTC, weescoelho approved these changes

2021-06-17 02:14 UTC, weescoelho approved these changes

2021-06-17 02:19 UTC, francisrod01 approved these changes

2021-06-17 02:19 UTC, merged