Feature/ad yf n gqh create componente date input
MeAjudaDev/greenwallet-react pull request #9
Opened 2021-06-19 23:07 UTC by weescoelho

2021-06-19 23:07 UTC, weescoelho commented
![](https://github.trello.services/images/mini-trello-icon.png) [[AdYfNGqh] - Criar componente Date Input](https://trello.com/c/AdYfNGqh/63-adyfngqh-criar-componente-date-input)

2021-06-20 03:43 UTC, stenioas requested changes

2021-06-20 03:43 UTC, stenioas commented on src/components/InputDate/InputDate.module.scss
> +
Linha final duplicada no fim do arquivo.

2021-06-20 03:43 UTC, stenioas commented on src/components/InputDate/index.js
> +export {default} from './InputDate'
Omissão de linha final do arquivo.

2021-06-20 03:43 UTC, stenioas commented on src/components/InputDate/InputDate.jsx
> +}
Omissão de linha final no arquivo.

2021-06-20 04:08 UTC, stenioas approved these changes

2021-06-20 07:42 UTC, francisrod01 approved these changes

2021-06-21 22:08 UTC, andremarcondesteixeira approved these changes

2021-06-21 22:08 UTC, merged